### ISSUE TITLE
Image url not transformed on build

### ISSUE THREAD

**Issue by sk337** [Lmmmmmm-bb/vite-plugin-open-graph#10]
When i use a relative url ex. `./src/favicon.ico` for any fields it does not get transformed during vite build and stays as the original url causing card to not render image

**Comment by thehands79** [comment]
Same same

**Comment by sk337** [comment]
@thehands79 
> Same same

i dont know why i didnt close this issue as i figured it out what i needed to do was import the image
ie my original example

```js
import image from "./src/favicon.ico";

return (
  <img src={image} />
)
```

**Comment by thehands79** [comment]
I ended up using the [public directory](https://vitejs.dev/guide/assets#the-public-directory) method.
