### ISSUE TITLE
Using 'name' instead of 'property'

### ISSUE THREAD

**Issue by livegp** [Lmmmmmm-bb/vite-plugin-open-graph#16]
When checking the card on the Facebook website using the link https://developers.facebook.com/tools/debug/, I get an error:

Tag specified as 'name' instead of 'property'

The following meta tags are specified using 'name' instead of 'property' and will be ignored unless specified using the 'property' key: fb:app_id

**Comment by Lmmmmmm-bb** [comment]
Thanks!
I mixed up the `meta` tag key of Twitter and Facebook.
Only the key of Twitter's Open Graph is `name`.
I will fix it later.

**Comment by Lmmmmmm-bb** [comment]
Just released **v2.1.2** to fix this issue.
